#cloud-config
hostname: RancherOS
rancher:
  network:
    interfaces:
      eth0:
        address: 192.168.50.101/24
        dhcp: false
        gateway: 192.168.50.254
        mtu: 1500
  services_include:
    open-vm-tools: true
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3fJENpz/belAO8rQNTPZHNugTTROZUTi5UEz2EoYDXDBWslYqxrIew1ajqHY6JEqf4mek+ZAmsVcOqZfGzg/6loFvw82WYMWErK6ylpW72swZktgLuWLCH3lwva3MKfrohL0wVOK8r++Cp4IZDpp922ihl14JB26nNKjmA7x7FWPXk9lqHbZNDfmDsUPLrjodhSwVs6Am2qnYtrtSK06S3ldZPzEhDI9UzlYSa2PnNaipAA6XBG51lKnPCkwrZNz62GBau9DqAyLvt6iViryaqv7cE6tYxFnF/R9sQPFqDcMRTgKyzTy2+KHnnfONh9ck7zMdz3fT4QiQBGM0d5HZ blacktha@gmail.com
