#cloud-config
hostname: Master
rancher:
  console: centos
  docker:
    registry_mirror: https://uxfagmza.mirror.aliyuncs.com
  system_docker:
    registry_mirror: https://uxfagmza.mirror.aliyuncs.com
  bootstrap_docker:
    registry_mirror: https://uxfagmza.mirror.aliyuncs.com
    tls: true
  network:
    interfaces:
      eth0:
        dhcp: true
  services_include:
    open-vm-tools: true
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4VnmbArPmO7ienvQw4Cw38Jat/HXDhAhVZH+8e9sHZFI9MNX1x2IUKj860q4nRe+ngBKdDG8FdBv5an7U7WyB6M2mQFwq5pKv0pcUx4sjabsLhoFVfrdvOzL92BOnITKh3wkjLeRfddX+J85DjP20KMuKG/Uvs07O555LNC477xYthYZlduEnBWhugvl6ZHnJTs3uPzSVnSW7vLdm5uGajgjRSKYBTybTPi6OFVeD8tuqBT2UyeD8CJuPk1Umn85KyfK1w6IFDb3c+aVsNTF1s/9+dnPbMC6R6yYmh/goYxMgavuvOPWeL7VZVOf5j1udwNyt6N/0swZoeFcLg1LF rancher@rancheros
